### PR TITLE
hopeing for a sticker in time

### PR DESCRIPTION
**Pull request by JonathanDagan**

### CODE REVIEW

**Comment by codediodeio** [comment]
missing submission

**Comment by JonathanDagan** [comment]
Excuse me for asking but what do you mean by missing submission? Since if
you are referring to the info I’m pretty sure I followed the right steps
but if I didn’t i would be happy know :)

**Comment by codediodeio** [comment]
I don't see the .txt file with your encoded address on the commit

**Comment by JonathanDagan** [comment]
Ok, so sorry for bothering but could I resubmit then?

**Comment by codediodeio** [comment]
Of course, there is still time

**Pull request closed without merging**
